name: Deploy Documentation

on:
  workflow_dispatch:
    inputs:
      subfolder:
        description: 'Subfolder for documentation (e.g., docs3, docsv3, docs). Leave empty for root deployment.'
        required: false
        default: ''
        type: string

# Ensure only latest deployment runs
concurrency:
  group: docs-deployment
  cancel-in-progress: true

jobs:
  merge-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          token: ${{ secrets.ORG_GH_TOKEN }}
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any additional dependencies if needed

      - name: Read branches config
        id: config
        run: |
          if [ ! -f "branches-config.json" ]; then
            echo "❌ branches-config.json not found!"
            exit 1
          fi
          echo "✅ Found branches-config.json"
          cat branches-config.json

      - name: Cleanup everything except preserved files
        run: |
          echo "🧹 Cleaning up everything except preserved files..."
          
          # Define files/folders to preserve during cleanup
          preserve_items=(
            ".gitignore"
            ".vale.ini"
            "branches-config.json"
            "README.md"
            ".github"
            ".devcontainer"
            ".vale"
            "scripts"
            ".git"
          )
          
          echo "📋 Files/folders to preserve:"
          printf '%s\n' "${preserve_items[@]}"
          
          # Clean everything (files and directories) except preserved items
          echo "🗑️  Removing all content except preserved items..."
          for item in *; do
            if [ -e "$item" ]; then
              # Check if this item should be preserved
              should_preserve=false
              for preserve_item in "${preserve_items[@]}"; do
                if [ "$item" = "$preserve_item" ]; then
                  should_preserve=true
                  break
                fi
              done
              
              if [ "$should_preserve" = false ]; then
                echo "  🗑️  Removing: $item"
                rm -rf "$item"
              else
                echo "  📁 Preserving: $item"
              fi
            fi
          done
          
          # Also clean hidden files/directories (except preserved ones)
          for item in .[^.]*; do
            if [ -e "$item" ]; then
              # Check if this item should be preserved
              should_preserve=false
              for preserve_item in "${preserve_items[@]}"; do
                if [ "$item" = "$preserve_item" ]; then
                  should_preserve=true
                  break
                fi
              done
              
              if [ "$should_preserve" = false ]; then
                echo "  🗑️  Removing hidden: $item"
                rm -rf "$item"
              else
                echo "  📁 Preserving hidden: $item"
              fi
            fi
          done
          
          echo "✅ Cleanup completed!"
          echo "📁 Remaining files after cleanup:"
          ls -la | head -10

      - name: Clone and organize branches
        run: |
          set -e
          
          echo "🔄 Starting branch cloning and organization..."
          
          # Process each version from branches-config.json
          python3 -c "
          import json
          import sys
          
          config = json.load(open('branches-config.json'))
          versions = config.get('versions', [])
          
          for v in versions:
              branch = v.get('branch', 'main')
              is_latest = v.get('isLatest', False)
              folder = v.get('folder', '')
              
              # Skip external versions
              if v.get('isExternal', False):
                  continue
                  
              if is_latest:
                  # Latest goes to root
                  print(f'root:{branch}')
              elif folder:
                  # Non-latest with folder goes to that folder
                  print(f'{folder}:{branch}')
          " > branch_list.txt
          
          echo "📋 Branches to process:"
          cat branch_list.txt
          
          # Process each branch
          while IFS=':' read -r target_dir branch_name; do
            if [ -n "$target_dir" ] && [ -n "$branch_name" ]; then
              echo "📂 Processing $target_dir from branch $branch_name..."
              
              # Create temporary directory for this branch
              temp_dir="temp_${target_dir}_${branch_name}"
              
              # Clone the specific branch
              echo "⬇️  Cloning branch $branch_name into $temp_dir..."
              git clone --single-branch --branch "$branch_name" --depth 1 \
                "https://github.com/${{ github.repository }}.git" "$temp_dir"
              
              if [ "$target_dir" = "root" ]; then
                # For root (latest), copy directly to current directory
                echo "📁 Moving contents from $temp_dir to root..."
                
                # Copy documentation content only, excluding development/build files
                find "$temp_dir" -mindepth 1 -maxdepth 1 \
                  ! -name '.git' \
                  ! -name 'scripts' \
                  ! -name 'branches-config.json' \
                  ! -name '.github' \
                  ! -name 'README.md' \
                  ! -name '.gitignore' \
                  ! -name '.devcontainer' \
                  ! -name '.vale' \
                  -exec cp -r {} . \;
                  
                echo "✅ Successfully organized root from branch $branch_name"
                echo "📋 Contents of root:"
                ls -la | head -10
              else
                # For non-root, create the target directory and copy there
                echo "📁 Moving contents from $temp_dir to $target_dir..."
                
                # Remove existing folder if it exists
                if [ -d "$target_dir" ]; then
                  echo "🗑️  Removing existing $target_dir/"
                  rm -rf "$target_dir"
                fi
                
                # Create target directory
                mkdir -p "$target_dir"
                
                # Copy documentation content only, excluding development/build files
                find "$temp_dir" -mindepth 1 -maxdepth 1 \
                  ! -name '.git' \
                  ! -name 'scripts' \
                  ! -name 'branches-config.json' \
                  ! -name '.github' \
                  ! -name 'README.md' \
                  ! -name '.gitignore' \
                  ! -name '.devcontainer' \
                  ! -name '.vale' \
                  -exec cp -r {} "$target_dir/" \;
                  
                echo "✅ Successfully organized $target_dir from branch $branch_name"
                echo "📋 Contents of $target_dir:"
                ls -la "$target_dir/" | head -10
              fi
              
              # Clean up temp directory
              rm -rf "$temp_dir"
            fi
          done < branch_list.txt
          
          # Clean up the branch list file
          rm -f branch_list.txt
          
          echo "🎉 All branches cloned and organized!"

      - name: Run docs merger
        run: |
          echo "🔄 Running documentation merger..."
          
          # Handle subfolder parameter properly
          # Distinguish between: no parameter, empty string, and specific value
          if [ -z "${{ github.event.inputs.subfolder }}" ]; then
            # No parameter provided - merge to root (no subfolder)
            USE_SUBFOLDER=false
            echo "📁 No subfolder parameter provided - merging to root"
          elif [ "${{ github.event.inputs.subfolder }}" = "" ]; then
            # Empty string provided - merge to root (no subfolder)  
            USE_SUBFOLDER=false
            echo "📁 Empty subfolder parameter provided - merging to root"
          else
            # Specific folder provided - use it
            SUBFOLDER="${{ github.event.inputs.subfolder }}"
            USE_SUBFOLDER=true
            echo "📁 Using subfolder: $SUBFOLDER"
          fi
          
          # Run the merge script with or without subfolder parameter
          if [ "$USE_SUBFOLDER" = true ]; then
            echo "🔧 Running merge with subfolder: $SUBFOLDER"
            python3 scripts/merge_docs_configs.py \
              --branches-config branches-config.json \
              --base-dir . \
              --subfolder "$SUBFOLDER" \
              --output docs.json
          else
            echo "🔧 Running merge to root (no subfolder parameter passed)"
            python3 scripts/merge_docs_configs.py \
              --branches-config branches-config.json \
              --base-dir . \
              --output docs.json
          fi
          
          echo "✅ Documentation merge completed!"

      - name: Cleanup cloned version folders
        run: |
          echo "🧹 Cleaning up temporary cloned version folders..."
          
          # Get current version folders from config
          current_folders=$(python3 -c "import json; config=json.load(open('branches-config.json')); folders=[v.get('folder','') for v in config.get('versions',[]) if v.get('folder','')]; print(' '.join(folders))")
          
          echo "📋 Removing cloned folders: $current_folders"
          
          # Remove the temporary cloned folders (they've been processed into subfolder structure)
          for folder in $current_folders; do
            if [ -n "$folder" ] && [ -d "$folder" ]; then
              echo "🗑️  Removing cloned folder: $folder/"
              rm -rf "$folder"
            fi
          done
          
          echo "✅ Cleanup of cloned folders completed!"

      - name: Verify output
        run: |
          echo "📋 Checking generated files..."
          
          if [ -f "docs.json" ]; then
            echo "✅ docs.json generated successfully"
            echo "📄 docs.json size: $(wc -c < docs.json) bytes"
            echo "🔍 First few lines of docs.json:"
            head -20 docs.json
          else
            echo "❌ docs.json not found!"
            exit 1
          fi
          
          echo ""
          echo "📁 Generated file structure:"
          find . -name "*.mdx" -o -name "*.md" -o -name "*.json" -o -name "*.css" -o -name "*.png" | head -20

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          branch: docs-merge-${{ github.run_number }}
          base: production
          title: "🤖 Auto-merge documentation from branches"
          body: |
            ## 📚 Documentation Merge Summary
            
            This PR contains automatically merged documentation from multiple branches.
            
            **Generated from:** `branches-config.json`  
            **Timestamp:** ${{ github.event.head_commit.timestamp }}  
            **Run ID:** ${{ github.run_id }}
            
            ### Changes Include:
            - ✅ Merged documentation from multiple branches
            - ✅ Generated unified `docs.json` configuration
            - ✅ Updated assets and content structure
            - ✅ Cleaned up outdated version folders
            
            ### Subfolder Used:
            `${{ github.event.inputs.subfolder || 'root (no subfolder)' }}`
            
            ---
            
            Please review the changes and merge when ready.
          commit-message: |
            🤖 Auto-merge documentation from branches
            
            Generated from branches-config.json at ${{ github.event.head_commit.timestamp }}
            
            - Merged documentation from multiple branches
            - Generated unified docs.json
            - Updated assets and content structure
          delete-branch: true
          draft: false
          maintainer-can-modify: true
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Enable auto-merge on deployment PR
        if: steps.create-pr.outputs.pull-request-number
        run: |
          PR_NUMBER="${{ steps.create-pr.outputs.pull-request-number }}"
          echo "🔄 Enabling auto-merge on deployment PR #$PR_NUMBER..."
          
          gh pr merge --squash --auto "$PR_NUMBER"
          
          echo "✅ Auto-merge enabled on PR #$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}

      - name: Create deployment summary
        run: |
          echo "## 📚 Documentation Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ✅ Successfully merged documentation" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Generated files:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`docs.json\` - Unified configuration" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "docs.json" ]; then
            echo "- Asset files (favicon.png, style.css, images/, etc.)" >> $GITHUB_STEP_SUMMARY
            echo "- Version folders with documentation content" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date)" >> $GITHUB_STEP_SUMMARY
