name: Trigger Documentation Deployment

on:
  push:
    branches:
      - main
      - 'release-*'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger production deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.ORG_GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-docs.yml/dispatches \
            -d '{"ref": "production"}'
