name: Trigger Documentation Deployment

on:
  push:
    branches:
      - main
      - 'release-*'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR information from commit
        id: get-pr
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MESSAGE"
          
          # Try to extract PR number from commit message
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oE '#[0-9]+' | head -1 | sed 's/#//')
          
          if [ -n "$PR_NUMBER" ]; then
            echo "Found PR number: #$PR_NUMBER"
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "has_pr=true" >> $GITHUB_OUTPUT
            
            # Extract PR title (everything before the PR number reference)
            PR_TITLE=$(echo "$COMMIT_MESSAGE" | sed 's/ (#[0-9]\+).*//' | head -1)
            echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
          else
            echo "No PR number found in commit message (direct push)"
            echo "has_pr=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger production deployment
        run: |
          # Prepare the dispatch payload
          if [ "${{ steps.get-pr.outputs.has_pr }}" = "true" ]; then
            PAYLOAD=$(jq -n \
              --arg ref "production" \
              --arg pr_number "${{ steps.get-pr.outputs.pr_number }}" \
              --arg pr_title "${{ steps.get-pr.outputs.pr_title }}" \
              --arg commit_sha "${{ github.sha }}" \
              --arg branch "${{ github.ref_name }}" \
              '{
                ref: $ref,
                inputs: {
                  triggering_pr_number: $pr_number,
                  triggering_pr_title: $pr_title,
                  triggering_commit_sha: $commit_sha,
                  triggering_branch: $branch
                }
              }')
            echo "Triggering deployment with PR #${{ steps.get-pr.outputs.pr_number }}"
          else
            PAYLOAD=$(jq -n \
              --arg ref "production" \
              --arg commit_sha "${{ github.sha }}" \
              --arg branch "${{ github.ref_name }}" \
              '{
                ref: $ref,
                inputs: {
                  triggering_commit_sha: $commit_sha,
                  triggering_branch: $branch
                }
              }')
            echo "Triggering deployment (direct push, no PR)"
          fi
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.ORG_GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-docs.yml/dispatches \
            -d "$PAYLOAD"
